export const blogs = [
    {
        image: "/blogs/47.jpg",
        name: "Jordan Craver",
        username: "@jordancraver",
        date: "Sep 28, 2024",
        title: "CSS view(): The Death of Javascript Scroll Animations",
        description: "How a 5-line CSS feature replaced 50+ lines of janky JavaScript and changed web animation forever",
        category: "Design",
    },
    {
        image: "/blogs/56.jpg",
        name: "Coy Tulp",
        username: "@coytulp",
        date: "Aug 14, 2024",
        title: "The Future of Server-Side Rendering: Trends for 2025",
        description: "SSR is evolving, and 2025 promises innovations that will change how we build the web — faster, smarter, and greener.",
        category: "Server",
    },
    {
        image: "/blogs/7.jpg",
        name: "Clinton Yellott",
        username: "@clintonott",
        date: "Nov 02, 2024",
        title: "Express.js Secrets That Senior Developers Don't Share",
        description: "Express.js has been the backbone of Node.js web development for years, but are you truly harnessing its full potential?",
        category: "Backend",
    },
    {
        image: "/blogs/8.jpg",
        name: "Duane Polman",
        username: "@duanepaulmon",
        date: "Dec 18, 2024",
        title: "Architectures of modern Front-end applications",
        description: "This post explores the advantages of popular architectures and helps you choose the best solution to meet your unique requirements.",
        category: "Design",
    },
    {
        image: "/blogs/69.jpg",
        name: "Thaddeus Arras",
        username: "@arrasthaddeus",
        date: "Jan 02, 2025",
        title: "Next.js 14+ Design Patterns: Best Practices for Modern Web Dev",
        description: "As Next.js continues to evolve, the release of Next.js 14+ brings new features and enhancements that enable developers to build applications.",
        category: "Frontend",
    },
    {
        image: "/blogs/77.jpg",
        name: "Graham Kappen",
        username: "@kappengraham",
        date: "Jan 21, 2025",
        title: "How to Build a Validated Multistep Form with ShadCN and React Hook Form",
        description: "If you’re developing a multistep form in Next.js, ensuring validation at every step can improve user experience.",
        category: "IT",
    },
    {
        image: "/blogs/65.jpg",
        name: "Tristan Zweck",
        username: "@tristanzweck",
        date: "Feb 01, 2025",
        title: "You must use middleware like this in Next.js",
        description: "Middleware in Next.js is often overlooked — but it’s a game-changer once you understand its potential.",
        category: "Security",
    },
    {
        image: "/blogs/66.jpg",
        name: "Herschel Bouey",
        username: "@harschelbuoey",
        date: "Aug 29, 2024",
        title: "The Real Reason OpenAI abandoned Next.js for Remix",
        description: "The surprising reasons behind OpenAI’s move and what it means for the future of web development.",
        category: "AI",
    },
    {
        image: "/blogs/46.jpg",
        name: "Herman Rodell",
        username: "@hermanrodell",
        date: "July 04, 2024",
        title: "React Component Reusability in Micro-Frontends",
        description: "Are you tired of reinventing the wheel every time you build a new micro-frontend? Do you find yourself copying and pasting React components",
        category: "Frontend",
    },
];